# Generated by Django 5.2.8 on 2025-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='My Portfolio', max_length=100),
        ),
    ]
