# Generated by Django 5.2.8 on 2025-12-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
            preserve_default=False,
        ),
    ]
