# Generated by Django 5.2.8 on 2026-02-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_holding_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='average_purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
